/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CursorGoaway
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var CursorGoaway = class extends import_obsidian.Plugin {
  async onload() {
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        let startTime;
        let isBlurring = false;
        const blurEditor = () => {
          var _a, _b;
          (_b = (_a = this.app.workspace.activeEditor) == null ? void 0 : _a.editor) == null ? void 0 : _b.blur();
          if (performance.now() - startTime < 500) {
            requestAnimationFrame(blurEditor);
          } else {
            isBlurring = false;
          }
        };
        this.cleanupKeydownHandler();
        if ((file == null ? void 0 : file.extension) === "md") {
          startTime = performance.now();
          isBlurring = true;
          requestAnimationFrame(blurEditor);
          const onKeyDown = (e) => {
            var _a;
            if (e.key !== "ArrowDown")
              return;
            const activeFile = this.app.workspace.getActiveFile();
            if ((activeFile == null ? void 0 : activeFile.path) !== file.path)
              return this.cleanupKeydownHandler();
            if (isBlurring)
              return;
            const editor = (_a = this.app.workspace.activeEditor) == null ? void 0 : _a.editor;
            if (editor) {
              const cm = editor.cm;
              if (cm && cm.hasFocus && cm.hasFocus()) {
                return this.cleanupKeydownHandler();
              }
            }
            const activeElement = document.activeElement;
            const editorContainer = activeElement == null ? void 0 : activeElement.closest(".cm-editor, .cm-content, .markdown-source-view");
            if (editorContainer) {
              return this.cleanupKeydownHandler();
            }
            e.preventDefault();
            if (editor) {
              try {
                editor.focus();
              } catch (err) {
                console.debug("focus() failed", err);
              }
              editor.setCursor(0, 0);
            }
            this.cleanupKeydownHandler();
          };
          document.addEventListener("keydown", onKeyDown, true);
          this.currentKeydownHandler = onKeyDown;
        }
      })
    );
  }
  /**
   * cleanup the keydown handler
   */
  cleanupKeydownHandler() {
    if (this.currentKeydownHandler) {
      document.removeEventListener("keydown", this.currentKeydownHandler, true);
      this.currentKeydownHandler = void 0;
    }
  }
  onunload() {
    this.cleanupKeydownHandler();
  }
};

/* nosourcemap */